flowchart  
    
    TB1[Acessar a tabela] --> TB2{Pessoa existe?}
    TB2 --sim--> P[Acessar o Persona</br>Menu Cadastro/Pessoas]
    TB2 --"não"--> TB3[Acrescentar usuário na tabela]
    TB3 --> P
    P --> P2
    P2[Conferir se a pessoa existe]
    P2 --> P3
    P3{Pessoa existe?} --sim--> T[Acessar o Tarifone</BR>Menu Cadastro/Contas]
    P3 --"não"--> P4[Novo usuário interno]
    P4 --> T
    T --> T2{Pesquisar usuario</br>e verificar conta atribuida}
    T2 --existe--> E[Acessar Explorer]
    T2 --"não existe"--> T3[Verificar o número</br>da última conta no</br>Explorer/Tabela]
    T3 --> T4
    T4[Criar nova conta</br>com o próximo</br>número disponível</br>e atribuir ao usuário]
    T4 --> E
    E --> E1[Acessar Plataforma/Contas] 
    E1 --> E2{Verificar se a conta do</br>Tarifone existe</br>no Explorer}
    E2 --existe--> S[Atualizar senha]
    E2 --"não existe"--> S1[Cadastrar conta</br>com o mesmo</br>número do Tarifone]
    S1 --> R[Definir uma senha]
    subgraph Acesso 
    R --> R1[Acesso]
    R1 --> R2[[Dar acesso:</br>-Local fixo</br>-Local celular</br>-DDD fixo</br>-DDD celular]]
    end
    S1 --> TB4[Atualizar usuário na tabela]
    S --> TB4
    TB4 --> EM[Enviar dados para o</br>e-mail cadastrado]
